-- CreateTable
CREATE TABLE "PortEntry" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "port" TEXT NOT NULL,
    "country" TEXT,
    "terminal" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "cargo" TEXT,
    "stowFactor" TEXT,
    "quantityInfo" TEXT,
    "waterDensity" TEXT,
    "maxDraftMeters" TEXT,
    "maxDraftNotes" TEXT,
    "loaMeters" TEXT,
    "beamMeters" TEXT,
    "maxDwtMt" TEXT,
    "airDraftMeters" TEXT,
    "minFreeboardMeters" TEXT,
    "loadRatePerDayMt" TEXT,
    "dischargeRatePerDayMt" TEXT,
    "agents" TEXT,
    "costDockage" TEXT,
    "costPilotage" TEXT,
    "costTowage" TEXT,
    "costTotalEstimate" TEXT,
    "bunkeringNotes" TEXT,
    "cleaningNotes" TEXT,
    "transitPsNotes" TEXT,
    "sulphurLimit" TEXT,
    "specialRestrictions" TEXT,
    "rawText" TEXT NOT NULL,

    CONSTRAINT "PortEntry_pkey" PRIMARY KEY ("id")
);
