const GLOBAL_CONDITION_CASES = [
  {
    id: "na-lb214-fw",
    enabled: true,
    region: "North America",
    name: "LB214 fresh water draft",
    port: "Long Beach",
    category: "draft",
    locationLabel: "LB214",
    observationValue: "12.8",
    expectedTags: ["FW"],
  },
  {
    id: "na-lb214-sw",
    enabled: true,
    region: "North America",
    name: "LB214 salt water draft",
    port: "Long Beach",
    category: "draft",
    locationLabel: "LB214",
    observationValue: "13.1",
    expectedTags: ["SW"],
  },
  {
    id: "na-vancouver-zero-tide",
    enabled: true,
    region: "North America",
    name: "Pacific Elevators zero tide draft",
    port: "Vancouver",
    category: "draft",
    locationLabel: "Pacific Elevators / Berth No. 4",
    observationValue: "13.2",
    expectedTags: ["Zero tide"],
  },
  {
    id: "cn-ningbo-density",
    enabled: true,
    region: "China",
    name: "Ningbo density-linked draft",
    port: "Ningbo",
    category: "draft",
    locationLabel: "CT3",
    observationValue: "14.5",
    expectedTags: ["Density 1.025"],
  },
  {
    id: "cn-majishan-tide-affected",
    enabled: true,
    region: "China",
    name: "Majishan tide-affected draft",
    port: "Majishan",
    category: "draft",
    locationLabel: "Ore Jetty / 3# Berth",
    observationValue: "15.0",
    expectedTags: ["Tide affected"],
  },
  {
    id: "in-kandla-arrival",
    enabled: true,
    region: "India / South Asia",
    name: "Kandla arrival draft",
    port: "Kandla",
    category: "draft",
    locationLabel: "Oil Jetty / Jetty No. 7",
    observationValue: "11.5",
    expectedTags: ["Arrival"],
  },
  {
    id: "in-kandla-departure",
    enabled: true,
    region: "India / South Asia",
    name: "Kandla departure draft",
    port: "Kandla",
    category: "draft",
    locationLabel: "Oil Jetty / Jetty No. 7",
    observationValue: "11.8",
    expectedTags: ["Departure"],
  },
  {
    id: "me-mesaieed-hw",
    enabled: true,
    region: "Middle East",
    name: "Mesaieed high-water draft",
    port: "Mesaieed",
    category: "draft",
    locationLabel: "Main Terminal / Berth A",
    observationValue: "12.8",
    expectedTags: ["HW"],
  },
  {
    id: "eu-piraeus-lw",
    enabled: true,
    region: "Europe / Black Sea / Med",
    name: "Piraeus low-water draft",
    port: "Piraeus",
    category: "draft",
    locationLabel: "Terminal II / Berth 3",
    observationValue: "11.9",
    expectedTags: ["LW"],
  },
  {
    id: "latam-santos-brackish",
    enabled: true,
    region: "Latin America",
    name: "Santos brackish draft",
    port: "Santos",
    category: "draft",
    locationLabel: "T-Granel / Berth 2",
    observationValue: "12.4",
    expectedTags: ["Brackish"],
  },
  {
    id: "af-richards-bay-naabsa",
    enabled: true,
    region: "Africa",
    name: "Richards Bay NAABSA draft",
    port: "Richards Bay",
    category: "draft",
    locationLabel: "CT / Berth 203",
    observationValue: "16.0",
    expectedTags: ["NAABSA"],
  },
  {
    id: "me-jebel-ali-sbm",
    enabled: true,
    region: "Middle East",
    name: "Jebel Ali SBM note",
    port: "Jebel Ali",
    category: "other",
    locationLabel: "CT2 / Berth 5",
    observationValue: "Mooring available",
    expectedTags: ["SBM"],
  },
  {
    id: "sea-hay-point-spm",
    enabled: true,
    region: "Southeast Asia / Australia",
    name: "Hay Point SPM note",
    port: "Hay Point",
    category: "other",
    locationLabel: "CT7",
    observationValue: "export line",
    expectedTags: ["SPM"],
  },
  {
    id: "cn-ningbo-cbm",
    enabled: true,
    region: "China",
    name: "Ningbo CBM note",
    port: "Ningbo",
    category: "other",
    locationLabel: "CT3",
    observationValue: "offshore support",
    expectedTags: ["CBM"],
  },
];

function getEnabledConditionCases() {
  return GLOBAL_CONDITION_CASES.filter((testCase) => testCase.enabled);
}

module.exports = {
  GLOBAL_CONDITION_CASES,
  getEnabledConditionCases,
};
