const GLOBAL_LOCATION_CASES = [
  {
    id: "na-long-beach-212",
    region: "North America",
    pattern: "compact terminal shorthand",
    enabled: true,
    name: "Long Beach shorthand 212",
    text: "Long Beach 212 draft 21m FW",
    expected: { port: "Long Beach", country: "US", terminal: "LB212", berth: null },
  },
  {
    id: "na-long-beach-lb-212",
    region: "North America",
    pattern: "spaced compact terminal shorthand",
    enabled: true,
    name: "Long Beach spaced shorthand",
    text: "Long Beach LB 212 draft now 16.8m FW",
    expected: { port: "Long Beach", country: "US", terminal: "LB212", berth: null },
  },
  {
    id: "na-long-beach-lb214",
    region: "North America",
    pattern: "explicit terminal code",
    enabled: true,
    name: "Long Beach explicit terminal",
    text: "LB214 max draft 12.8m SW at Long Beach",
    expected: { port: "Long Beach", country: "US", terminal: "LB214", berth: null },
  },
  {
    id: "na-pittsburg-pbg6-terminal-inheritance",
    region: "North America",
    pattern: "single terminal dossier inherits terminal context",
    enabled: true,
    name: "Pittsburg PBG6 inherited terminal restriction",
    text: "Pittsburg PBG6 Max Draft (Pittsburg and Stockton are impacted by these river drafts): NYPT to PBG3 DECREASED from 35.1 to 32.9; PBG3 to Antioch Pt DECREASED from 35.1 to 33.4",
    expected: { port: "Pittsburg", country: "USA", terminal: "Pittsburg PBG6", berth: null },
    expectedStoredFacts: [
      {
        category: "draft",
        scope: "TERMINAL",
        terminal: "Pittsburg PBG6",
      },
    ],
  },
  {
    id: "na-cemex-natural",
    region: "North America",
    pattern: "operator plus berth",
    enabled: true,
    name: "Cemex berth natural order",
    text: "Cemex berth 32 discharge 9000 mt/day at Long Beach",
    expected: { port: "Long Beach", country: "US", terminal: "Cemex", berth: "Berth 32" },
  },
  {
    id: "na-cemex-reversed",
    region: "North America",
    pattern: "berth plus operator reversed order",
    enabled: true,
    name: "Cemex berth reversed order",
    text: "Berth 32 Cemex draft 11.8m Long Beach",
    expected: { port: "Long Beach", country: "US", terminal: "Cemex", berth: "Berth 32" },
  },
  {
    id: "na-cemex-compact",
    region: "North America",
    pattern: "operator plus compact berth number",
    enabled: true,
    name: "Long Beach operator plus compact berth",
    text: "Long Beach Cemex 32 berth density 1.025",
    expected: { port: "Long Beach", country: "US", terminal: "Cemex", berth: "Berth 32" },
  },
  {
    id: "na-vancouver-g3-compact",
    region: "North America",
    pattern: "compact terminal alias",
    enabled: true,
    name: "Vancouver compact terminal",
    text: "Vancouver G3 draft 13.0m",
    expected: { port: "Vancouver", country: "Canada", terminal: "G3 Terminal", berth: null },
  },
  {
    id: "na-vancouver-g3-explicit",
    region: "North America",
    pattern: "explicit terminal alias",
    enabled: true,
    name: "Vancouver explicit G3",
    text: "G3 Terminal Vancouver load rate 24000 mt/day",
    expected: { port: "Vancouver", country: "Canada", terminal: "G3 Terminal", berth: null },
  },
  {
    id: "na-vancouver-pacific-elevator-singular",
    region: "North America",
    pattern: "singular plural operator spelling",
    enabled: true,
    name: "Pacific Elevators singular spelling",
    text: "Pacific Elevator berth 4 density 1.025 in Vancouver",
    expected: { port: "Vancouver", country: "Canada", terminal: "Pacific Elevators", berth: "Berth No. 4" },
  },
  {
    id: "na-vancouver-pacific-elevator-plural",
    region: "North America",
    pattern: "plural operator spelling",
    enabled: true,
    name: "Pacific Elevators plural spelling",
    text: "Vancouver Pacific Elevators berth no. 4 draft 13.2m",
    expected: { port: "Vancouver", country: "Canada", terminal: "Pacific Elevators", berth: "Berth No. 4" },
  },
  {
    id: "cn-ningbo-ct3",
    region: "China",
    pattern: "container terminal code",
    enabled: true,
    fixtureNeeded: true,
    name: "Ningbo CT3 draft",
    text: "Ningbo CT3 draft 14.5m",
    expected: { port: "Ningbo", country: "China", terminal: "CT3", berth: null },
  },
  {
    id: "cn-majishan-3-berth",
    region: "China",
    pattern: "hash-number berth style",
    enabled: true,
    fixtureNeeded: true,
    name: "Majishan hash berth",
    text: "Majishan 3# berth density 1.025",
    expected: { port: "Majishan", country: "China", terminal: "Ore Jetty", berth: "3# Berth" },
  },
  {
    id: "cn-beilun-phase-2",
    region: "China",
    pattern: "phase-based terminal naming",
    enabled: true,
    fixtureNeeded: true,
    name: "Beilun phase terminal",
    text: "Ningbo Beilun Phase 2 max loa 225m",
    expected: { port: "Ningbo", country: "China", terminal: "Phase 2", berth: null },
  },
  {
    id: "cn-ore-berth-no-1",
    region: "China",
    pattern: "berth no style",
    enabled: false,
    fixtureNeeded: true,
    name: "Ore berth number style",
    text: "Ore berth no.1 discharge 30000 mt/day at Ningbo",
    expected: { port: "Ningbo", country: "China", terminal: "Ore Terminal", berth: "Berth No. 1" },
  },
  {
    id: "cn-xingang-c1",
    region: "China",
    pattern: "alphanumeric sub-terminal code",
    enabled: false,
    fixtureNeeded: true,
    name: "Xingang C1 shorthand",
    text: "Xingang C1 draft 13.8m at Tianjin",
    expected: { port: "Tianjin", country: "China", terminal: "Xingang C1", berth: null },
  },
  {
    id: "in-kandla-oil-jetty-7",
    region: "India / South Asia",
    pattern: "jetty plus number",
    enabled: true,
    fixtureNeeded: true,
    name: "Kandla oil jetty",
    text: "Kandla oil jetty no.7 draft 11.5m",
    expected: { port: "Kandla", country: "India", terminal: "Oil Jetty", berth: "Jetty No. 7" },
  },
  {
    id: "in-vizag-eq-berth",
    region: "India / South Asia",
    pattern: "abbreviated berth name",
    enabled: false,
    fixtureNeeded: true,
    name: "Vizag EQ berth",
    text: "Vizag EQ berth load rate 18000 mt/day",
    expected: { port: "Vizag", country: "India", terminal: null, berth: "EQ Berth" },
  },
  {
    id: "in-paradip-south-quay",
    region: "India / South Asia",
    pattern: "quay plus berth number",
    enabled: false,
    fixtureNeeded: true,
    name: "Paradip south quay",
    text: "Paradip south quay berth 3 density 1.018",
    expected: { port: "Paradip", country: "India", terminal: "South Quay", berth: "Berth 3" },
  },
  {
    id: "sea-semarang-indonesia",
    region: "Southeast Asia",
    pattern: "explicit Southeast Asia country resolution",
    enabled: true,
    fixtureNeeded: true,
    name: "Semarang explicit Indonesia",
    text: "Semarang, Indonesia max draft 10.5m",
    expected: { port: "Semarang", country: "Indonesia", terminal: null, berth: null },
  },
  {
    id: "sea-siam-commercial-seaport",
    region: "Southeast Asia",
    pattern: "terminal hint resolves Thailand country",
    enabled: true,
    fixtureNeeded: true,
    name: "Siam Commercial Seaport country hint",
    text: "Siam Commercial Seaport max draft 10.5m",
    expected: { port: "Siam", country: "Thailand", terminal: "Siam Commercial Seaport", berth: null },
  },
  {
    id: "me-mesaieed-berth-a",
    region: "Middle East",
    pattern: "berth letter style",
    enabled: true,
    fixtureNeeded: true,
    name: "Mesaieed berth letter",
    text: "Mesaieed berth A max draft 12.8m",
    expected: { port: "Mesaieed", country: "Qatar", terminal: "Main Terminal", berth: "Berth A" },
  },
  {
    id: "me-jebel-ali-ct2-berth-5",
    region: "Middle East",
    pattern: "terminal code plus berth number",
    enabled: true,
    fixtureNeeded: true,
    name: "Jebel Ali CT2 berth",
    text: "Jebel Ali ct2 berth 5 load rate 25000 mt/day",
    expected: { port: "Jebel Ali", country: "UAE", terminal: "CT2", berth: "Berth 5" },
  },
  {
    id: "me-ruwais-industrial-jetty-2",
    region: "Middle East",
    pattern: "industrial jetty numbered",
    enabled: false,
    fixtureNeeded: true,
    name: "Ruwais industrial jetty",
    text: "Ruwais industrial jetty no.2 density 1.024",
    expected: { port: "Ruwais", country: "UAE", terminal: "Industrial Jetty", berth: "Jetty No. 2" },
  },
  {
    id: "eu-constanta-south-117",
    region: "Europe / Black Sea / Med",
    pattern: "berth number in terminal area",
    enabled: false,
    fixtureNeeded: true,
    name: "Constanta South berth",
    text: "Constanta South berth 117 draft 13.5m",
    expected: { port: "Constanta", country: "Romania", terminal: "South", berth: "Berth 117" },
  },
  {
    id: "eu-antwerp-deurganckdok-1732",
    region: "Europe / Black Sea / Med",
    pattern: "dock name plus berth number",
    enabled: true,
    fixtureNeeded: true,
    name: "Antwerp dock berth",
    text: "Antwerp Deurganckdok berth 1732 air draft 53m",
    expected: { port: "Antwerp", country: "Belgium", terminal: "Deurganckdok", berth: "Berth 1732" },
  },
  {
    id: "eu-piraeus-terminal-ii-berth-3",
    region: "Europe / Black Sea / Med",
    pattern: "roman numeral terminal",
    enabled: true,
    fixtureNeeded: true,
    name: "Piraeus terminal roman numeral",
    text: "Piraeus terminal II berth 3 density 1.020",
    expected: { port: "Piraeus", country: "Greece", terminal: "Terminal II", berth: "Berth 3" },
  },
  {
    id: "latam-tubarao-pier-ii",
    region: "Latin America",
    pattern: "pier roman numeral",
    enabled: false,
    fixtureNeeded: true,
    name: "Tubarao pier roman numeral",
    text: "Tubarao pier ii draft 15.2m",
    expected: { port: "Tubarao", country: "Brazil", terminal: "Pier II", berth: null },
  },
  {
    id: "latam-santos-t-granel-2",
    region: "Latin America",
    pattern: "hyphenated terminal plus berth",
    enabled: true,
    fixtureNeeded: true,
    name: "Santos T-Granel berth",
    text: "Santos t-granel berth 2 load rate 28000 mt/day",
    expected: { port: "Santos", country: "Brazil", terminal: "T-Granel", berth: "Berth 2" },
  },
  {
    id: "latam-san-nicolas-muelle-3",
    region: "Latin America",
    pattern: "Spanish quay naming",
    enabled: false,
    fixtureNeeded: true,
    name: "San Nicolas muelle",
    text: "San Nicolas muelle 3 draft 10.8m",
    expected: { port: "San Nicolas", country: "Argentina", terminal: null, berth: "Muelle 3" },
  },
  {
    id: "af-richards-bay-203",
    region: "Africa",
    pattern: "terminal abbreviation plus berth number",
    enabled: true,
    fixtureNeeded: true,
    name: "Richards Bay CT berth",
    text: "Richards Bay ct berth 203 draft 16.0m",
    expected: { port: "Richards Bay", country: "South Africa", terminal: "CT", berth: "Berth 203" },
  },
  {
    id: "af-saldanha-ore-jetty-1",
    region: "Africa",
    pattern: "ore jetty numbered",
    enabled: false,
    fixtureNeeded: true,
    name: "Saldanha ore jetty",
    text: "Saldanha ore jetty no.1 load rate 40000 mt/day",
    expected: { port: "Saldanha", country: "South Africa", terminal: "Ore Jetty", berth: "Jetty No. 1" },
  },
  {
    id: "af-tema-quay-2",
    region: "Africa",
    pattern: "quay number",
    enabled: false,
    fixtureNeeded: true,
    name: "Tema quay",
    text: "Tema quay 2 density 1.019",
    expected: { port: "Tema", country: "Ghana", terminal: null, berth: "Quay 2" },
  },
  {
    id: "sea-hay-point-ct7",
    region: "Southeast Asia / Australia",
    pattern: "coal terminal code",
    enabled: true,
    fixtureNeeded: true,
    name: "Hay Point CT7",
    text: "Hay Point ct7 draft 17.0m",
    expected: { port: "Hay Point", country: "Australia", terminal: "CT7", berth: null },
  },
  {
    id: "sea-dbct-berth-1",
    region: "Southeast Asia / Australia",
    pattern: "compact terminal code plus berth",
    enabled: false,
    fixtureNeeded: true,
    name: "DBCT berth",
    text: "DBCT berth 1 load rate 45000 mt/day",
    expected: { port: "Dalrymple Bay", country: "Australia", terminal: "DBCT", berth: "Berth 1" },
  },
  {
    id: "sea-kooragang-3",
    region: "Southeast Asia / Australia",
    pattern: "terminal area plus berth number",
    enabled: false,
    fixtureNeeded: true,
    name: "Kooragang berth",
    text: "Newcastle Kooragang 3 berth draft 15.0m",
    expected: { port: "Newcastle", country: "Australia", terminal: "Kooragang", berth: "Berth 3" },
  },
];

function getEnabledLocationCases() {
  return GLOBAL_LOCATION_CASES.filter((testCase) => testCase.enabled);
}

function summarizeCorpus() {
  const byRegion = new Map();

  for (const testCase of GLOBAL_LOCATION_CASES) {
    const current = byRegion.get(testCase.region) ?? { total: 0, enabled: 0 };
    current.total += 1;
    if (testCase.enabled) current.enabled += 1;
    byRegion.set(testCase.region, current);
  }

  return Array.from(byRegion.entries()).map(([region, counts]) => ({
    region,
    ...counts,
  }));
}

module.exports = {
  GLOBAL_LOCATION_CASES,
  getEnabledLocationCases,
  summarizeCorpus,
};
